# Generated by Django 4.1.2 on 2022-11-06 14:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyBase',
            fields=[
                ('code', models.CharField(help_text='Identifying code based on ISO 3166-1 alpha-2 code for countries', max_length=6, primary_key=True, serialize=False)),
                ('wikipedia_link', models.URLField(blank=True, help_text='Link to the Wikipedia page', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(help_text='ISO 639-1 code', max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Language name in the language itself', max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('geographybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flagschallenge.geographybase')),
            ],
            bases=('flagschallenge.geographybase',),
        ),
        migrations.CreateModel(
            name='TerritoryGroup',
            fields=[
                ('geographybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flagschallenge.geographybase')),
                ('typology', models.CharField(choices=[('CON', 'Continent'), ('ARE', 'Area'), ('CTR', 'Country'), ('POL', 'Political'), ('OTH', 'Other')], default='CON', help_text='Typology of a territory group (e.g. Continent, Geographical area, Political organization, etc.)', max_length=3)),
            ],
            bases=('flagschallenge.geographybase',),
        ),
        migrations.CreateModel(
            name='TerritoryName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Territory name in the language', max_length=100)),
                ('language', models.ForeignKey(help_text='Language reference', on_delete=django.db.models.deletion.CASCADE, related_name='territoryname_set', to='flagschallenge.language')),
                ('territory', models.ForeignKey(help_text='Territory reference', on_delete=django.db.models.deletion.CASCADE, related_name='territoryname_set', to='flagschallenge.geographybase')),
            ],
        ),
        migrations.AddIndex(
            model_name='territoryname',
            index=models.Index(fields=['territory', 'language'], name='territory_language_idx'),
        ),
        migrations.AddConstraint(
            model_name='territoryname',
            constraint=models.UniqueConstraint(fields=('territory', 'language'), name='unique_territory_language'),
        ),
        migrations.AddField(
            model_name='territory',
            name='groups',
            field=models.ManyToManyField(help_text='The groups that this territory belongs to (e.g. Continent, Geographical area, Political organization, etc.)', related_name='territories', to='flagschallenge.territorygroup'),
        ),
    ]
