# Generated by Django 4.1.2 on 2022-10-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagschallenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorygroup',
            name='typology',
            field=models.CharField(choices=[('CON', 'Continent'), ('ARE', 'Area'), ('CTR', 'Country'), ('POL', 'Political'), ('OTH', 'Other')], default='CON', help_text='Typology of a territory group (e.g. Continent, Geographical area, Political organization, etc.)', max_length=3),
        ),
    ]
